@Dapper_Micro_Optimizations_HostAddress = http://localhost:5082

GET {{Dapper_Micro_Optimizations_HostAddress}}/weatherforecast/
Accept: application/json

###
@productId = 2779ee47-10b0-4bd7-8342-404006aa1392
 
###
GET {{Dapper_Micro_Optimizations_HostAddress}}/api/products?page=1&pageSize=100

###
GET {{Dapper_Micro_Optimizations_HostAddress}}/api/products/{{productId}}?includeReviews=true

### 
POST {{Dapper_Micro_Optimizations_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Keyboard",
  "price": 34.99
}


###
POST {{Dapper_Micro_Optimizations_HostAddress}}/api/products/{{productId}}/reviews
Content-Type: application/json

{
  "reviewer": "Kevin Kelo",
  "stars": 3
}

### 
PUT {{Dapper_Micro_Optimizations_HostAddress}}/api/products/{{productId}}
Content-Type: application/json

{
    "name": "chocolate bar",
    "price": 3.50
}

### DELETE
DELETE {{Dapper_Micro_Optimizations_HostAddress}}/api/products/{{productId}}
